version: '3.7'

services:
  # Ubuntu Laravel
  app:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: app
    hostname: app
    volumes:
    - .:/app/admin
    ports:
    - "80:80"
    - "443:443"
    networks:
    - app-network

  # Postgres Service
  db:
    image: postgres:12.1-alpine
    container_name: db
    restart: unless-stopped
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
    - "5432:5432"
    networks:
    - app-network

  # Redis
  redis:
    image: redis:6.0-rc-alpine
    container_name: redis
    restart: unless-stopped
    ports:
    - "6379:6379"
    networks:
    - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  pgdata:
    driver: local
