version: '3.7'

services: 
    admin:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: admin
        hostname: admin
        volumes: 
        - .:/app/project
        ports: 
        - "9000:80"
        networks: 
        - backend
networks: 
    backend:
        name: backend
